### ISSUE TITLE
message not creating a commit with just `gec`

### ISSUE THREAD

**Issue by zachboatwright** [sodiumhalogenteam/git-emoji-commit#1]
![](https://sh-drop.s3.us-east-1.amazonaws.com/zb/Screen%20Shot%202018-09-05%20at%203.49.29%20PM.png)

Just $ `gec` and adding in title/message doesn't create a commit.

**Comment by chancesmith** [comment]
@SZBoatwright, I'm not getting the same thing. What is your $`git-emoji-commit --version`?

![](https://sh-drop.s3.us-east-1.amazonaws.com/cs/gec%20issue%202018-12-03%2004.50.20.png)

Try an update and see if you get the same thing:
$`npm update -g git-emoji-commit`

**Comment by zachboatwright** [comment]
@chancesmith I think it was the version, I've since upgraded to the most recent version and am no longer getting the issue

**Comment by chancesmith** [comment]
yeah, I just confirmed this is working
